export  const   MAKE_BOOKING_REQUEST = "MAKE_BOOKING_REQUEST";
export  const  MAKE_BOOKING_SUCCESS = "MAKE_BOOKING_SUCCESS";
export  const  MAKE_BOOKING_FAIL = "MAKE_BOOKING_FAIL";

export  const   BOOKED_VENUE_REQUEST = "BOOKED_VENUE_REQUEST";
export  const  BOOKED_VENUE_SUCCESS = "BOOKED_VENUE_SUCCESS";
export  const  BOOKED_VENUE_FAIL = "BOOKED_VENUE_FAIL";

export  const  SAVE_BOOKING_DATE = "SEND_BOOKING_DATE";
