export  const REQUEST_RESERVATION_REQUEST = "REQUEST_RESERVATION_REQUEST";
export  const  REQUEST_RESERVATION_SUCCESS = "REQUEST_RESERVATION_SUCCESS";
export  const  REQUEST_RESERVATION_FAIL = "REQUEST_RESERVATION_FAIL";