export  const REQUEST_RESERVATION_REQUEST = "REQUEST_RESERVATION_REQUEST";
export  const  REQUEST_RESERVATION_SUCCESS = "REQUEST_RESERVATION_SUCCESS";
export  const  REQUEST_RESERVATION_FAIL = "REQUEST_RESERVATION_FAIL";


export  const RESERVED_VENUE_LIST_REQUEST = "RESERVED_VENUE_LIST_REQUEST";
export  const  RESERVED_VENUE_LIST_SUCCESS = "RESERVED_VENUE_LIST_SUCCESS";
export  const  RESERVED_VENUE_LIST_FAIL = "RESERVED_VENUE_LIST_FAIL";
